name: Bug report 🐛
description: If something isn't working as expected 🤔.

body:
  - type: markdown
    attributes:
      value: |
        ## Before reporting an issue please check that you are using the latest PHPStan version!

  - type: textarea
    attributes:
      label: Bug report
      description: Please describe your problem here.
    validations:
      required: true

  - type: input
    attributes:
      label: Code snippet that reproduces the problem
      description: Try to reproduce the issue you are facing using https://phpstan.org/try and post the unique URL here
      placeholder: https://phpstan.org/r/<unique_id>

  - type: textarea
    attributes:
      label: Expected output
      description: Was the issue reported incorrectly? Or should PHPStan detect an issue with the code but doesn't?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Did PHPStan help you today? Did it make you happy in any way?
      description: |
        Answering this question is not required, but if you have anything positive to share, please do so here!
        Sometimes we get tired of reading bug reports all day and a little positive end note does wonders.
        Idea by Joey Hess, https://joeyh.name/blog/entry/two_holiday_stories/
